export { default as Header } from './Header'
export { default as SignUpPage } from './SignUpPage'
export { default as LogInPage } from './LogInPage'
export { default as HomePage } from './HomePage'
export { default as ProfilePage } from './ProfilePage'
export { default as Collections } from './Collections'